// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace DOCUMENTMANAGER.Models;

public partial class DOCMANAGERContext : DbContext
{
    public DOCMANAGERContext(DbContextOptions<DOCMANAGERContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Document> Document { get; set; }

    public virtual DbSet<Login> Login { get; set; }

    public virtual DbSet<UserRegistration> UserRegistration { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Document>(entity =>
        {
            entity.HasKey(e => e.DocId).HasName("Pk_Document_Doc_Id");

            entity.Property(e => e.DocId).HasColumnName("Doc_Id");
            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasMaxLength(1000);
            entity.Property(e => e.UploadDate).HasColumnType("datetime");

            entity.Property(e => e.User_Id).HasColumnName("User_Id");
        });

        modelBuilder.Entity<Login>(entity =>
        {
            entity.ToTable("LOGIN");

            entity.Property(e => e.LoginId).HasColumnName("Login_Id");
            entity.Property(e => e.IsLogin).HasColumnName("Is_Login");
            entity.Property(e => e.LoginDate)
                .HasColumnType("datetime")
                .HasColumnName("Login_Date");
            entity.Property(e => e.LoginToken)
                .IsUnicode(false)
                .HasColumnName("Login_Token");
            entity.Property(e => e.UserId).HasColumnName("User_Id");
        });

        modelBuilder.Entity<UserRegistration>(entity =>
        {
            entity.HasKey(e => e.UserId);

            entity.ToTable("User_Registration");

            entity.Property(e => e.UserId).HasColumnName("User_Id");
            entity.Property(e => e.ConfirmPassword)
                .HasMaxLength(100)
                .HasColumnName("Confirm_Password");
            entity.Property(e => e.Email).HasMaxLength(150);
            entity.Property(e => e.Gender)
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Password).HasMaxLength(100);
            entity.Property(e => e.UserName)
                .HasMaxLength(150)
                .HasColumnName("User_Name");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}