// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace DOCUMENTMANAGER.Models;

public partial class Document
{
    public long DocId { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public DateTime UploadDate { get; set; }

    [ForeignKey("user")] 
    public long? User_Id { get; set; }

    public virtual UserRegistration user { get; set; }
}